- name: Create RG-vnet-subnet-NSG
  hosts: localhost
  connection: local
  vars_files:
  - ./vars/vars.yml
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ az_resource_group_name }}"
      location: "{{ az_resource_group_location }}"
      tags:
        Owner: "{{ az_owner_tag }}"
  - name: Create a virtual network
    azure_rm_virtualnetwork:
      name: "{{ az_vnet_name }}"
      resource_group: "{{ az_resource_group_name }}"
      address_prefixes_cidr: "{{ az_vnet_cidr }}"
