---
- name: Create Vnet
  hosts: localhost
  connection: local
  tasks:
  - name: Create a virtual network
    azure_rm_virtualnetwork:
      name: buizerdvnet
      resource_group: BuizerdRG
      address_prefixes_cidr:
          - "10.22.0.0/16"
      dns_servers:
          - "127.0.0.1"
          - "127.0.0.2"
      tags:
          testing: testing
          delete: on-exit
