- name: Create RG
  hosts: localhost
  connection: local
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: BuizerdRG
      location: westeu
      tags:
          testing: testing
          delete: never
