- name: Create subnet
  hosts: localhost
  connection: local
  tasks:
  - name: Create a subnet
    azure_rm_subnet:
      name: buizerdsubnet01
      virtual_network_name: buizerdvnet
      resource_group: BuizerdRG
      address_prefix_cidr: '10.22.1.0/16'
