- name: Create Application Gateway
  hosts: localhost
  connection: local
  tasks:
  - name: Create instance of Application Gateway
    azure_rm_appgw:
      resource_group: buizerdRG
      name: buizerdag01
      sku:
        name: standard_small
        tier: standard
        capacity: 2
      gateway_ip_configurations:
        - subnet:
          id: GatewaySubnet
          name: app_gateway_ip_config
      frontend_ip_configurations:
        - public_ip_address: appgwpublicip
          name: sample_gateway_frontend_ip_config
      frontend_ports:
        - port: 80
          name: ag_frontend_port
      backend_address_pools:
        - backend_addresses:
          - ip_address: 10.23.1.4
          name: test_backend_address_pool
      backend_http_settings_collection:
        - port: 80
          protocol: http
          cookie_based_affinity: enabled
          name: sample_appgateway_http_settings
      http_listeners:
        - frontend_ip_configuration: sample_gateway_frontend_ip_config
          frontend_port: ag_frontend_port
          name: sample_http_listener
      request_routing_rules:
        - rule_type: Basic
          backend_address_pool: test_backend_address_pool
          backend_http_settings: sample_appgateway_http_settings
          http_listener: sample_http_listener
          name: rule1
    register: output